### ISSUE TITLE
Lowercase name in CMS backend

### ISSUE THREAD

**Issue by akien-mga** [pcvonz/oc-patreongoalstatus-plugin#1]
See in `/backend/system/updates`:
![image](https://user-images.githubusercontent.com/4701338/30418460-56b9caec-9933-11e7-9ddf-e51f6ffbe3bb.png)
No biggie, but still worth fixing to match other plugins ;)
I'd also suggest to capitalize "Patreon" in the description.

**Comment by pcvonz** [comment]
Fixed!
